export const GET_CARD_NUMBER = "GET_CARD_NUMBER";
export const GET_CARD_NUMBER_ERROR = "GET_CARD_NUMBER_ERROR";

export const CARD_NUMBER_REMOVE = "CARD_NUMBER_REMOVE";
export const CARD_NUMBER_REMOVE_ERROR = "CARD_NUMBER_REMOVE_ERROR";

export const CARD_NUMBER_ADD_ERROR = "CARD_NUMBER_ADD_ERROR";

export const CARD_NUMBER_ADD_PRICE = "CARD_NUMBER_ADD_PRICE";
export const CARD_NUMBER_ADD_PRICE_ERROR = "CARD_NUMBER_ADD_PRICE_ERROR";
